/** @format */

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import {useEffect} from "react";
import Footer from "@/components/footer";
import RootModals from "@/components/modals";
import ReduxProvider from "./ReduxProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className="bg-white">
          <RootModals />
          {false ? (
            <div className="h-screen">{children}</div>
          ) : (
            <div className="flex">
<Sidebar/>
<div className="flex flex-col w-full">
{/* <Header/> */}
<div className=" border border-rounded" > {children}</div> </div>

</div> 
            // <div className="flex">
            //   {/* <Sidebar /> */}
            //   <div className="w-full">
            //     <Header />
            //     <div className="w-full bg-white border rounded-lg">
            //       {children}
            //     </div>
            //     <Footer />
            //   </div>
            // </div>
          )}
        </body>
      </html>
    </ReduxProvider>
  );
}

{
  /* <div className="flex">
<Sidebar/>
<div className="flex flex-col w-full">
<Header/>
<div className=" border border-rounded" > {children}</div> </div>

</div> */
}
