/** @format */

import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import {useEffect} from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-white">
        {false ? (
          <div className="h-screen">{children}</div>
        ) : (
          <div className="flex">
            {/* <Sidebar /> */}
            <div className="w-full">
              <Header />
              <div className="w-full bg-white border rounded-lg">
                {children}
              </div>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}

{
  /* <div className="flex">
<Sidebar/>
<div className="flex flex-col w-full">
<Header/>
<div className=" border border-rounded" > {children}</div> </div>

</div> */
}
